### ISSUE TITLE
Hand-tag 20 threads, with a variety of 1/2/3/4 thread types

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#1]
Use `tagger.py` to hand tag at least 20 threads. If you do this on more than one Subreddit, just slap all your .csv files together into one. Upload your final .csv file to the `data` subdirectory (create it if you're the first) underneath `HandTag`.

**Comment by akochans** [comment]
Added Alexis

**Comment by divilian** [comment]
all done!
