### ISSUE TITLE
Read Soliman

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#18]
For Monday

**Comment by TromboneDavies** [comment]
Remove bots, link handling, political subreddits (use for #30)

**Comment by TromboneDavies** [comment]
They use both posts and comments because they're looking for left vs right, we're using only comments because we're looking at nature of the discorse

**Comment by TromboneDavies** [comment]
Idea: Run this dude's code to see if there is any coloration between polarization and political context
