### ISSUE TITLE
Add your assessments to everyone else's hand-tagged threads

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#2]
For each `.txt` file in the `data` directory (under `HandTag`) that *doesn't* start with "`piggied_`", if you're the second person to tag it, run the `piggyBackTagger.py` to add your assessments to it, this will create a `piggied_` file. At this point, do a "`git rm`" on the original file, since the `piggied_` version will now have both your assessments and the original owner's.

For each `piggied_` file that you haven't added your assessments to yet, run the `completeTagger.py` script on it to add your assessments to it.

**Comment by divilian** [comment]
=Here's the process=

- For Alexis's: Stephen adds his, then TJ adds his, then Veronica adds hers
- For Stephen's: TJ adds his, then Veronica, then Alexis
- For TJ: Veronica, then Alexis, then Stephen
- For Veronica: Alexis then Stephen then TJ

**Comment by divilian** [comment]
As of 8:30pm June 10th, here's the status as far as I can tell:
- `alexistags.csv` (now `piggied_alexistags.csv`) has Stephen's added, still needs @TromboneDavies's and then Veronica's
- `stephenstags.csv` still needs @TromboneDavies's, then Veronica's, then Alexis's
- `tjtags.csv` (now `piggied_tjtags.csv`) has Veronica's added, still needs @akochans's, then Stephen's
- `veronicatags.csv` still needs @akochans's, Stephen's, then TJ's

Reply to this comment with a correction if I have any of that wrong.

**Comment by akochans** [comment]
Stephen can now do piggied_tjtags.csv and piggied_veronica_tags.csv

**Comment by divilian** [comment]
Stephen's assessments now added to `piggied_tjtags.csv`, which I believe is our first totally completed data set! Yay team

**Comment by divilian** [comment]
Stephen's assessments now added to `piggied_veronica_tags.csv`, which is now ready for @TromboneDavies.

**Comment by TromboneDavies** [comment]
piggied_veronica is up

**Comment by TromboneDavies** [comment]
piggied_stephenstags is up

**Comment by divilian** [comment]
As of today 6/11:
- `piggied_tjtags.csv`: done (and even named right)
- `piggied_veronica_tags.csv`: only missing TJ
- `piggied_alexistags.csv`: still needs TJ, and then Veronica
- `piggied_stephen.csv`: still needs Veronica, and then Alexis

**Comment by TromboneDavies** [comment]
Just added my tags to piggied_alexis

**Comment by vgcagle** [comment]
I tagged piggied_alexistags, so I think that one is complete!

**Comment by vgcagle** [comment]
I added my tags to piggied_stephenstags

**Comment by TromboneDavies** [comment]
I added my tags to piggied_veronica

**Comment by akochans** [comment]
I have completed piggied_stephen.csv
I believe this issue has been completed!
