### ISSUE TITLE
Seek out some more non-polarized threads

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#27]
Currently, we have 76 polarized 34 non-polarized. Possibly look here:
- abortiondebate
- moderatepolitics
- neutralpolitics
- politicaldiscussion
Use TJ's original tagger.py script to add 10-ish (hopefully mostly non-polarized) threads to a **`yournameExtra.csv`** file.

**Comment by divilian** [comment]
Be prepared to reconcile all these as a group at Monday's meeting!

**Comment by divilian** [comment]
Remember, here is the order:

Alexis => Stephen => TJ => Veronica => Alexis => ...

**Comment by vgcagle** [comment]
I forgot to add (#27), but Veronica assessed tjExtra

**Comment by akochans** [comment]
I also just forgot to add #27, Alexis assessment of piggied_tjExtra

**Comment by divilian** [comment]
Status check: I think we're now completely done, except that @akochans has to do `piggied_stephenExtra.csv` and @TromboneDavies has to do `piggied_veronicaExtra.csv`, right?

If so, go team! We can reconcile these in tomorrow's meeting.

**Comment by divilian** [comment]
Done! And all reconciled.
