### ISSUE TITLE
Make cheat sheet for github usage

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#34]
Include:
- clone
- add
- commit
- commit -a
- push
- pull
- diff (or difftool)  (point to p.223 of Blueprints)
- status
- log

**Comment by divilian** [comment]
Do @vgcagle and @akochans still think this would be useful?

**Comment by akochans** [comment]
For right now I think I am good!

**Comment by vgcagle** [comment]
I'm good too, I can always use the two chapters of Blueprints as a reference.

**Comment by divilian** [comment]
Closed for now since my awesome students are too smart and self-motivated to even need this.
