### ISSUE TITLE
Look at Purpletag

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#37]
Find the Python code for "Purpletag" (referenced in Hemphill 2016) and download it and play around with it. Could it be applied to Reddit threads instead of to Congresspeople? (And is it only for hashtags, or does it also do text?)

**Comment by akochans** [comment]
from README.md https:// github.com/casmlab/purpletag/releases/tag/v1.0. doi:10.5281/zenodo.53888

- "purpletag consists of a number of command-line tools to collect, parse, and analyze tweets sent by members of Congress." four commands are collect, parse, score, and serve
- "collect" command specifically gets tweets from members of congress listed in twitter.yaml (I do not know what this is)
- "parse" command specifically gets the hashtags used by each MOC
- "score" command scores hashtags according to their polarity.
    - "The tags' scores are computed by the following approach:
    1. Compute the Chi-squared value for each hashtag (i.e., how correlated is it with a party?)
    2. Determine the signed version of this score (i.e., is it more indicative of liberals (-) or conservatives (+).
    3. Compute the z-score for all tags in this file."

Considering the score, the thing that tells us either polarized or not polarized, is based specifically on hashtags according to the README.md, I am not quite sure how we would use this. The score is based on how correlated a given hashtag is with a party when we already have the knowledge of each MOC's party alignment.

**Comment by divilian** [comment]
Good job, @akochans. I think we can file this away for now then. One possible way this could resurface is in using a Yang 2016 style approach for identifying "keywords" (non-hashtag words that are nevertheless highly correlated with certain labels; essentially, a culled version of the mostInformativeWords) and then using something like Purpletag on those not-hashtags-but-sort-of-behaving-like-hashtags words.

Putting to sleep for now.
