### ISSUE TITLE
Chase Hemphill references *forwards* in time

### ISSUE THREAD

**Issue by divilian** [TromboneDavies/PolarOps#6]
Add to Zotero whatever looks worth adding

**Comment by TromboneDavies** [comment]
https://scholar.google.com/scholar?start=0&hl=en&as_sdt=5,47&sciodt=0,47&cites=132361489265275191&scipsc=#:~:text=From%20Twitter%20to%20Charlottesville%3A%20Analyzing%20the%20fighting%20words%20between%20the%20alt-right%20and%20Antifa

https://www.tandfonline.com/doi/full/10.1080/19331681.2019.1651685?casa_token=yorTl843c_QAAAAA%3Ar6AcOLRE5VXcl3XeV2An7eJMPlBDheX9ffT-CvaAh5EYsTk6GoUQWFKdvBzlc6sZ_xVihiFNXKiBYg

https://dl.acm.org/doi/abs/10.1145/3439827?casa_token=G8WbANiDTbYAAAAA%3AQXCVJ-KGSEyH0oGYNf1V0R7H3XManjvlPg8W4UXK2oDY29VMyXNX1sdUwdOT9FN9ywKr3yG_Gy6zGg

https://ojs.aaai.org/index.php/ICWSM/article/view/7297

https://arxiv.org/abs/1906.04836
